# Generated by Django 4.1.4 on 2023-01-17 07:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_user_order_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_user',
            name='number',
            field=models.CharField(default=0, max_length=11, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='main_user',
            name='bought',
            field=models.ManyToManyField(blank=True, related_name='main_users', to='main.content'),
        ),
    ]
