# Generated by Django 4.1.4 on 2023-01-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_main_user_number_alter_main_user_bought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=models.SlugField(),
        ),
    ]
