# Generated by Django 4.1.4 on 2023-02-07 07:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.CharField(blank=True, max_length=11, validators=[django.core.validators.MinLengthValidator(11)])),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('number', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(8)])),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=200)),
                ('time', models.TimeField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sorena.coach')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sorena.field')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gyms', to='sorena.gym')),
            ],
        ),
        migrations.CreateModel(
            name='Sorena_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)])),
                ('national_id', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('birthyear', models.IntegerField(validators=[django.core.validators.MinValueValidator(1300), django.core.validators.MaxValueValidator(1402)])),
                ('birthmonth', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('birthday', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('start_insurance_year', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1300), django.core.validators.MaxValueValidator(1402)])),
                ('start_insurance_month', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('start_insurance_day', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('coach', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='sorena.coach')),
                ('field', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='sorena.field')),
            ],
        ),
    ]
