# Generated by Django 4.1.4 on 2023-02-07 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorena', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorena_user',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='sorena_user',
            name='field',
        ),
    ]
