# Generated by Django 4.1.4 on 2023-02-07 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sorena', '0002_remove_sorena_user_coach_remove_sorena_user_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorena_user',
            name='coach',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='sorena.coach'),
        ),
        migrations.AddField(
            model_name='sorena_user',
            name='field',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='sorena.field'),
        ),
    ]
