# Generated by Django 4.1.4 on 2023-02-07 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorena', '0003_sorena_user_coach_sorena_user_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorena_user',
            name='start_insurance_day',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='sorena_user',
            name='start_insurance_month',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='sorena_user',
            name='start_insurance_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1300), django.core.validators.MaxValueValidator(1402)]),
        ),
    ]
