# Generated by Django 4.1.4 on 2023-02-07 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sorena', '0004_alter_sorena_user_start_insurance_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorena_user',
            name='coach',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sorena.coach'),
        ),
        migrations.AlterField(
            model_name='sorena_user',
            name='field',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sorena.field'),
        ),
    ]
