# Generated by Django 4.1.4 on 2023-02-07 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorena', '0005_alter_sorena_user_coach_alter_sorena_user_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sorena_user',
            old_name='national_id',
            new_name='national',
        ),
    ]
